project:
  type: website
  output-dir: docs
  preview: 
    port: 4200
    browser: false

website:
  title: "My Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: flatly
    css: styles.css

editor: source

