project:
  type: website
  output-dir: docs
  preview: 
    port: 4200
    browser: false

website:
  title: "Alex Labuda's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/alexlabuda
      - icon: linkedin
        href: https://www.linkedin.com/in/alex-labuda/
      - icon: arrow-right-square
        text: Portfolio
        href: https://alex-labuda-portfolio.netlify.app/
      - icon: bar-chart
        href: https://public.tableau.com/app/profile/alexlabuda
format:
  html:
    theme: flatly
    css: styles.css

editor: source

